-- ======================================================================================
-- DDL: Gold Dimension - dimProvider (Healthcare Practitioner & Organization)
-- Standard: HL7 FHIR R4 (Practitioner / PractitionerRole / Organization Mapping)
-- Schema: claimsprocessing.gold.gold_dimprovider
-- Description: Conformed Gold dimension table capturing healthcare provider demographic,
--              specialty, taxonomy, network, and organizational metadata with SCD Type 2 tracking.
-- ======================================================================================

CREATE TABLE IF NOT EXISTS claimsprocessing.gold.gold_dimprovider (
    provider_key                           BIGINT        COMMENT 'Surrogate primary key (SCD Type 2)',
    provider_id                            STRING        COMMENT 'Natural unique provider business identifier',
    effective_start_date                   DATE          COMMENT 'SCD Type 2 effective start date',
    effective_end_date                     DATE          COMMENT 'SCD Type 2 effective end date (NULL if active)',
    is_current                             INT           COMMENT 'SCD Type 2 current record indicator flag (1=Current, 0=Historical)',
    npi                                    STRING        COMMENT 'National Provider Identifier (10-digit NPI standard)',
    tin                                    STRING        COMMENT 'Tax Identification Number (TIN / EIN)',
    last_name                              STRING        COMMENT 'Provider family / last name or facility name',
    first_name                             STRING        COMMENT 'Provider given / first name',
    middle_name                            STRING        COMMENT 'Provider middle initial or secondary given name',
    phone_number                           STRING        COMMENT 'Primary contact telephone number',
    address1                               STRING        COMMENT 'Primary practice location street address line 1',
    address2                               STRING        COMMENT 'Primary practice location street address line 2',
    city                                   STRING        COMMENT 'Practice location city',
    state                                  STRING        COMMENT 'Practice location state two-letter postal code',
    zip_code                               STRING        COMMENT 'Practice location ZIP / postal code',
    practice_code                          STRING        COMMENT 'Practice / facility location identifier',
    practice_name                          STRING        COMMENT 'Practice / facility location name',
    provider_org_code                      STRING        COMMENT 'Parent provider organization / PO code',
    provider_org_name                      STRING        COMMENT 'Parent provider organization / PO name',
    provider_specialty_description         STRING        COMMENT 'Human-readable primary specialty description',
    taxonomy_code_1                        STRING        COMMENT 'Primary NUCC Healthcare Provider Taxonomy Code',
    hp_specialty_code_1                    STRING        COMMENT 'Primary Health Plan specific specialty code',
    adv_provider_specialty_code_1          STRING        COMMENT 'Primary advanced provider specialty code',
    taxonomy_code_2                        STRING        COMMENT 'Secondary taxonomy code',
    hp_specialty_code_2                    STRING        COMMENT 'Secondary health plan specialty code',
    adv_provider_specialty_code_2          STRING        COMMENT 'Secondary advanced provider specialty code',
    taxonomy_code_3                        STRING        COMMENT 'Tertiary taxonomy code',
    hp_specialty_code_3                    STRING        COMMENT 'Tertiary health plan specialty code',
    adv_provider_specialty_code_3          STRING        COMMENT 'Tertiary advanced provider specialty code',
    taxonomy_code_4                        STRING        COMMENT 'Quaternary taxonomy code',
    hp_specialty_code_4                    STRING        COMMENT 'Quaternary health plan specialty code',
    adv_provider_specialty_code_4          STRING        COMMENT 'Quaternary advanced provider specialty code',
    taxonomy_code_5                        STRING        COMMENT 'Quinary taxonomy code',
    hp_specialty_code_5                    STRING        COMMENT 'Quinary health plan specialty code',
    adv_provider_specialty_code_5          STRING        COMMENT 'Quinary advanced provider specialty code',
    is_prescribe_privilege                 STRING        COMMENT 'Prescribing authority privilege indicator (Y/N)',
    provider_dea                           STRING        COMMENT 'Drug Enforcement Administration (DEA) registration number',
    payer_id                               STRING        COMMENT 'Associated Health Plan / Payer identifier',
    is_contracted                          STRING        COMMENT 'Network participation contracted flag (Y/N)',
    provider_hai                           STRING        COMMENT 'Hospital Affiliation Identifier',
    hospital_id                            STRING        COMMENT 'Primary admitting hospital identifier',
    is_excluded_from_provider_reporting    STRING        COMMENT 'Flag indicating exclusion from provider reporting',
    alt_prov_reporting_1                   STRING        COMMENT 'Alternate provider reporting attribute tier 1',
    alt_prov_reporting_2                   STRING        COMMENT 'Alternate provider reporting attribute tier 2',
    alt_prov_reporting_3                   STRING        COMMENT 'Alternate provider reporting attribute tier 3',
    alt_prov_reporting_4                   STRING        COMMENT 'Alternate provider reporting attribute tier 4',
    alt_prov_reporting_5                   STRING        COMMENT 'Alternate provider reporting attribute tier 5',
    alt_prov_reporting_6                   STRING        COMMENT 'Alternate provider reporting attribute tier 6',
    alt_prov_reporting_7                   STRING        COMMENT 'Alternate provider reporting attribute tier 7',
    alt_prov_reporting_8                   STRING        COMMENT 'Alternate provider reporting attribute tier 8',
    alt_prov_reporting_9                   STRING        COMMENT 'Alternate provider reporting attribute tier 9',
    alt_prov_reporting_10                  STRING        COMMENT 'Alternate provider reporting attribute tier 10',
    program_type                           STRING        COMMENT 'Risk adjustment program classification (e.g. Targeted)',
    practice_targeted_status               STRING        COMMENT 'Targeted practice engagement status',
    product_id                             STRING        COMMENT 'Healthcare product association identifier',
    provider_type                          STRING        COMMENT 'Provider classification type (Individual, Group, Facility)'
) USING delta
COMMENT 'HL7 FHIR R4 Standardized Gold Dimension Table for Healthcare Providers (Practitioner / Organization)';
