-- ======================================================================================
-- DDL: Gold Dimension - dimProvider (Healthcare Practitioner & Organization)
-- Standard: HL7 FHIR R4 (Practitioner / PractitionerRole / Organization Mapping)
-- Schema: claimsprocessing.gold.gold_dimprovider
-- Description: Conformed Gold dimension table capturing healthcare provider demographic,
--              specialty, taxonomy, network, and organizational metadata with SCD Type 2 tracking.
-- ======================================================================================

CREATE TABLE IF NOT EXISTS claimsprocessing.gold.gold_dimprovider (
    providerKey                             BIGINT        COMMENT 'Surrogate primary key (SCD Type 2)',
    ESAIInternalProviderID                 STRING        COMMENT 'Natural unique provider business identifier',
    identifier_npi                          STRING        COMMENT 'National Provider Identifier (NPI)',
    identifier_tin                          STRING        COMMENT 'Tax Identification Number (TIN / EIN)',
    identifier_providerDEA                  STRING        COMMENT 'DEA registration number',
    identifier_payerID                      STRING        COMMENT 'Health Plan / Payer identifier',
    identifier_hospitalID                   STRING        COMMENT 'Admitting hospital identifier',
    name_family                             STRING        COMMENT 'Provider family / last name or facility name',
    name_given_first                        STRING        COMMENT 'Provider given / first name',
    name_given_middle                       STRING        COMMENT 'Provider middle initial or secondary given name',
    telecom_phone                           STRING        COMMENT 'Primary contact telephone number',
    address_line1                           STRING        COMMENT 'Practice street address line 1',
    address_line2                           STRING        COMMENT 'Practice street address line 2',
    address_city                            STRING        COMMENT 'Practice city',
    address_state                           STRING        COMMENT 'Practice state',
    address_postalCode                      STRING        COMMENT 'Practice ZIP / postal code',
    practiceCode                            STRING        COMMENT 'Practice / facility location identifier',
    practiceName                            STRING        COMMENT 'Practice / facility location name',
    providerOrgCode                         STRING        COMMENT 'Parent provider organization code',
    providerOrgName                         STRING        COMMENT 'Parent provider organization name',
    providerSpecialtyDescription            STRING        COMMENT 'Primary specialty description',
    taxonomyCode1                           STRING        COMMENT 'Primary NUCC Taxonomy Code',
    hpSpecialtyCode1                        STRING        COMMENT 'Primary Health Plan specialty code',
    advProviderSpecialtyCode1               STRING        COMMENT 'Primary advanced provider specialty code',
    taxonomyCode2                           STRING        COMMENT 'Secondary taxonomy code',
    hpSpecialtyCode2                        STRING        COMMENT 'Secondary health plan specialty code',
    advProviderSpecialtyCode2               STRING        COMMENT 'Secondary advanced provider specialty code',
    taxonomyCode3                           STRING        COMMENT 'Tertiary taxonomy code',
    hpSpecialtyCode3                        STRING        COMMENT 'Tertiary health plan specialty code',
    advProviderSpecialtyCode3               STRING        COMMENT 'Tertiary advanced provider specialty code',
    taxonomyCode4                           STRING        COMMENT 'Quaternary taxonomy code',
    hpSpecialtyCode4                        STRING        COMMENT 'Quaternary health plan specialty code',
    advProviderSpecialtyCode4               STRING        COMMENT 'Quaternary advanced provider specialty code',
    taxonomyCode5                           STRING        COMMENT 'Quinary taxonomy code',
    hpSpecialtyCode5                        STRING        COMMENT 'Quinary health plan specialty code',
    advProviderSpecialtyCode5               STRING        COMMENT 'Quinary advanced provider specialty code',
    extension_isPrescribePrivilege          STRING        COMMENT 'Prescribing authority privilege flag',
    extension_isContracted                  STRING        COMMENT 'Network participation contracted flag',
    extension_providerHAI                   STRING        COMMENT 'Hospital Affiliation Identifier',
    extension_isExcludedFromProviderReporting STRING      COMMENT 'Exclusion from provider reporting flag',
    extension_programType                   STRING        COMMENT 'Risk adjustment program classification',
    extension_practiceTargetedStatus        STRING        COMMENT 'Targeted practice engagement status',
    extension_ProductID                     STRING        COMMENT 'Healthcare product association identifier',
    extension_ProviderType                  STRING        COMMENT 'Provider classification type',
    identifier_alternateKey1                STRING        COMMENT 'Alternate Key 1',
    identifier_alternateKey2                STRING        COMMENT 'Alternate Key 2',
    identifier_alternateKey3                STRING        COMMENT 'Alternate Key 3',
    identifier_alternateKey4                STRING        COMMENT 'Alternate Key 4',
    identifier_alternateKey5                STRING        COMMENT 'Alternate Key 5',
    identifier_alternateKey6                STRING        COMMENT 'Alternate Key 6',
    identifier_alternateKey7                STRING        COMMENT 'Alternate Key 7',
    identifier_alternateKey8                STRING        COMMENT 'Alternate Key 8',
    identifier_alternateKey9                STRING        COMMENT 'Alternate Key 9',
    identifier_alternateKey10               STRING        COMMENT 'Alternate Key 10',
    effectiveStartDate                      DATE          COMMENT 'SCD Type 2 effective start date',
    effectiveEndDate                        DATE          COMMENT 'SCD Type 2 effective end date',
    isCurrent                               BOOLEAN       COMMENT 'SCD Type 2 current record indicator flag'
) USING delta;

