-- ======================================================================================
-- DDL: Silver Staging - silver_provider_hierarchy (Provider Hierarchy Staging)
-- Standard: HL7 FHIR R4 (PractitionerRole / Organization Alignment)
-- Schema: claimsprocessing.silver.silver_provider_hierarchy
-- Description: Staging table capturing 4-tier provider practice, organization, and location hierarchies.
-- ======================================================================================

CREATE TABLE IF NOT EXISTS claimsprocessing.silver.silver_provider_hierarchy (
    client_id                   STRING        COMMENT 'Client identification string',
    file_id                     BIGINT        COMMENT 'Ingestion file control identifier',
    load_date_time              TIMESTAMP     COMMENT 'Pipeline ingestion timestamp',
    file_layout_id              STRING        COMMENT 'File layout format identifier',
    file_layout_description     STRING        COMMENT 'File layout description',
    provider_id                 STRING        COMMENT 'Provider business identifier',
    provider_last_name          STRING        COMMENT 'Provider last name',
    provider_npi                STRING        COMMENT 'Provider National Provider Identifier (NPI)',
    location_group_id           STRING        COMMENT 'Location group identifier',
    location_ranking            INT           COMMENT 'Location priority ranking index',
    location_id_type            STRING        COMMENT 'Location ID classification type',
    location_id                 STRING        COMMENT 'Practice location identifier',
    location_desc               STRING        COMMENT 'Practice location description / name',
    location_tin                STRING        COMMENT 'Practice location Tax Identification Number (TIN)',
    location_address1           STRING        COMMENT 'Location street address line 1',
    location_address2           STRING        COMMENT 'Location street address line 2',
    location_city               STRING        COMMENT 'Location city',
    location_state              STRING        COMMENT 'Location state two-letter code',
    location_zip                STRING        COMMENT 'Location ZIP code',
    county_code                 STRING        COMMENT 'County FIPS / ISO code',
    phone_number                STRING        COMMENT 'Practice phone number',
    fax_number                  STRING        COMMENT 'Practice fax number',
    contact_person              STRING        COMMENT 'Practice contact person name',
    do_not_chase                STRING        COMMENT 'Do not chase flag',
    tier2_id_type               STRING        COMMENT 'Tier 2 Organization ID type',
    tier2_id                    STRING        COMMENT 'Tier 2 Organization ID (Provider Org / PO Code)',
    tier2_desc                  STRING        COMMENT 'Tier 2 Organization description (Provider Org / PO Name)',
    tier2_address1              STRING        COMMENT 'Tier 2 street address line 1',
    tier2_address2              STRING        COMMENT 'Tier 2 street address line 2',
    tier2_city                  STRING        COMMENT 'Tier 2 city',
    tier2_state                 STRING        COMMENT 'Tier 2 state',
    tier2_zip                   STRING        COMMENT 'Tier 2 ZIP code',
    tier3_id_type               STRING        COMMENT 'Tier 3 Health System / Network ID type',
    tier3_id                    STRING        COMMENT 'Tier 3 Health System ID',
    tier3_desc                  STRING        COMMENT 'Tier 3 Health System description / name',
    tier3_address1              STRING        COMMENT 'Tier 3 address line 1',
    tier3_address2              STRING        COMMENT 'Tier 3 address line 2',
    tier3_city                  STRING        COMMENT 'Tier 3 city',
    tier3_state                 STRING        COMMENT 'Tier 3 state',
    tier3_zip                   STRING        COMMENT 'Tier 3 ZIP code',
    tier4_id_type               STRING        COMMENT 'Tier 4 Parent Corporation ID type',
    tier4_id                    STRING        COMMENT 'Tier 4 Parent Corporation ID',
    tier4_desc                  STRING        COMMENT 'Tier 4 Parent Corporation description',
    tier4_address1              STRING        COMMENT 'Tier 4 address line 1',
    tier4_address2              STRING        COMMENT 'Tier 4 address line 2',
    tier4_city                  STRING        COMMENT 'Tier 4 city',
    tier4_state                 STRING        COMMENT 'Tier 4 state',
    tier4_zip                   STRING        COMMENT 'Tier 4 ZIP code',
    start_date                  TIMESTAMP     COMMENT 'Relationship effective start date',
    end_date                    TIMESTAMP     COMMENT 'Relationship effective end date',
    hash_key                    STRING        COMMENT 'CDC Hash key'
) USING delta
COMMENT 'HL7 FHIR R4 Standardized Silver Staging Table for Provider Hierarchies';
